[package]
name = "sodiboo-feed-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
atom_syndication = "0.12.3"
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive", "cargo"] }
rss = "2.0.8"
webpage = "2.0.1"
